apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: isv-managed-starburst-operator-validate-isv-webhook-service
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    control-plane: validation-webhook-manager
status:
  loadBalancer: {}
